name: ci

on:
  pull_request:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sh-lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        lint: [shellcheck, shfmt]

    steps:
      - uses: actions/checkout@v4
      - name: Install Packages
        run: sudo apt update && sudo apt install -y ${{ matrix.lint }}
      - name: lint
        run: |
          if [ ${{ matrix.lint }} == "shfmt"]; then
              shfmt -w -i 2 build.sh
          else
              ${{ matrix.lint }} build.sh
          fi

  yaml-lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: yarn global add yaml-lint
      - run: yamllint action.yml

  build:
    runs-on: ubuntu-latest
    needs: 
      - sh-lint
      - yaml-lint
    strategy:
      fail-fast: false

    steps:
      - uses: sekaimoe/aosp_clang_action@main
